CREATE TABLE Person (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY ,
                        middle_name VARCHAR(20) NOT NULL UNIQUE,
                        first_name VARCHAR(20) NOT NULL,
                        last_name VARCHAR(20) NOT NULL,
                        address VARCHAR(255) NOT NULL,
                        employment_info VARCHAR(255) NOT NULL,
                        phone_number VARCHAR(13) NOT NULL,
                        credit_status VARCHAR(255) NOT NULL,
                        requestedAmount BIGINT
);

CREATE TABLE passport (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          passport_number VARCHAR(20) NOT NULL,
                          user_id BIGINT UNIQUE REFERENCES Person(id) ON DELETE CASCADE
);

-- Добавляем столбцы для даты создания и даты обновления в таблице "Person"
ALTER TABLE Person
    ADD COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ADD COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

-- Добавляем столбцы для даты создания и даты обновления в таблице "passport"
ALTER TABLE passport
    ADD COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ADD COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;