CREATE TABLE IF NOT EXISTS LoanEntity (
                                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                        userId BIGINT,
                                        requstedAmount NUMERIC(19,2),
                                        signingStatus VARCHAR(128),
                                        applicationDate TIMESTAMP
);